<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPgw4rxh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPgw4rxh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPgw4rxh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPgw4rxh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPgw4rxh\appProdProjectContainer([
    'container.build_hash' => 'Pgw4rxh',
    'container.build_id' => '196870ae',
    'container.build_time' => 1699290911,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPgw4rxh');
